### ISSUE TITLE
Run without recursive?

### ISSUE THREAD

**Issue by seonghobae** [yencarnacion/html4tree#2]
Hello,
I want to run without recursive features. Can I do that?

**Comment by yencarnacion** [comment]
@seonghobae 

If I understood you correctly, you are concerned with the recursion introduced by the Kotlin extension walkTopDown.

The answer to your question is then that to avoid recursion one would have to write a non-recursive version of the Kotlin extension walkTopDown.

```
fun File.walkTopDown(): FileTreeWalk
```
See the tail recursive function gotoNext() in https://github.com/JetBrains/kotlin/blob/master/libraries/stdlib/jvm/src/kotlin/io/files/FileTreeWalk.kt#L95

At the moment, I am not inclined to re-write walkTopDown in a non-recursive manner because it would be overkill for my simple use case.  However, pull requests are welcome.

Donald Knuth said “premature optimization is the root of all evil.”  See https://en.wikiquote.org/wiki/Donald_Knuth

**Comment by yencarnacion** [comment]
@seonghobae

If you absolutely have to eliminate recursion you can walk the File tree using a stack or a queue.

Search Google for `How do I traverse a tree without using recursion?`

You will find answers such as:

https://softwareengineering.stackexchange.com/questions/226155/how-do-i-traverse-a-tree-without-using-recursion

**Comment by yencarnacion** [comment]
I addressed your issue by re-writing the code so as to not be recursive.

**Comment by seonghobae** [comment]
Humm, I meant avoiding recursive saving index.html per directory. The tree structure is no matter to me; however, I don't want to save index.html recursive (automatically).

**Comment by yencarnacion** [comment]
@seonghobae

I made a change so that the program now allows a user to only generate the index.html file for the top directory:

`$ java -jar ./build/libs/html4tree.jar <top directory to index> --max-level 0`

you can also vary how deep it will save to by changing `--max-level`

Let me know if this functionality is what you were looking for.

If the above change does not meet your need,  please give a few examples of how you would like the program to work.  I do not promise that I will implement the required changes ... but I might.
